# Workflow to submit a forecast to the EFI Forecasting Challenge. This script is
# for the code. For more elaboration on each step, see submit.html
# 
# Anna Spiers
# June 2021

# Learning Objectives -----------------------------------------------------

# In this tutorial, you will learn how to:  
# 1. Register a team   
# 2. Generate a forecast file  
# 3. Generate an associated metadata file  
# 4. Submit your forecast and metadata files  
# 5. Visualize your submission  


library(here)         # Manage working directories
library(neon4cast)
library(dplyr)

wd <- here("04_submit_forecast")

# 1. Create team  ---------------------------------------------------------
# Register at https://nd.qualtrics.com/jfe/form/SV_9MJ29y2xNrBOjqZ


# 2. Create forecast  -----------------------------------------------------

# Read in forecast generated by Alexey
fc_raw <- readr::read_csv(file.path(wd,"data","forecast-2021-05-15.csv"))
head(fc_raw)

# Add columns necessary for phenology challenge
# time, siteID, ensemble or statistic, forecast, data_assimilation, gcc_90
fc_raw %>% 
    mutate(siteID = "HARV",
           forecast = 1,
           data_assimilation = 0) %>%
    rename(gcc_90 = gcc_pred) %>%
    relocate(siteID, .after = time) %>%
    relocate(gcc_90, .after = data_assimilation) %>%
    head()

forecast <- fc_raw %>% 
    mutate(siteID = "HARV",
           forecast = 1,
           data_assimilation = 0) %>%
    rename(gcc_90 = gcc_pred) %>%
    relocate(siteID, .after = time) %>%
    relocate(gcc_90, .after = data_assimilation) 

# Write the forecast to a file following EFI naming conventions:
forecast_file <- glue::glue(file.path(wd,"data","{theme}-{date}-{team}.csv"),
                            theme = "phenology",
                            date = Sys.Date(),
                            team = "wigglaspen")
readr::write_csv(forecast, forecast_file)

# Validate saved forecast
forecast_output_validator(forecast_file)

# Score saved forecast locally once target data become available for date range
scores <- score(forecast, theme = "phenology")
scores %>% 
  group_by(siteID, target) %>% 
  summarise(mean_score = mean(score, na.rm=TRUE))


# 3. Create metadata ------------------------------------------------------

# Step 1: Create a yaml file that has the same name as your forecast file. Manually enter your forecast details 
create_model_metadata(forecast_file)

# Step 2: Convert the yaml to an eml (xml) file for submission
metadata_yaml <- glue::glue(file.path(wd, "data", "{theme}-{team}.yml"),
                            theme = "phenology",
                            team = "wigglaspen")
# Generate xml from yaml
write_metadata_eml(forecast_file = forecast_file,
                   metadata_yaml = metadata_yaml,
                   forecast_issue_time = Sys.Date(),
                   forecast_iteration_id = "1")


# 4. Submit! --------------------------------------------------------------

# Use the neon4cast::submit() function
metadata_xml <- glue::glue(file.path(wd, "data", "{theme}-{date}-{team}.xml"),
                            theme = "phenology", 
                            date=Sys.Date(),
                            team = "wigglaspen")
# By default, you must manually type Yes in console to confirm submission
submit(forecast_file, metadata = metadata_xml)



# 5. View results ---------------------------------------------------------

# View submitted forecast on the Shiny dashborad (https://shiny.ecoforecast.org/)

